export class GSTR3B{
    month_year:any;
    sales_rate_InMaha:any;
    sales_basic_InMaha:any;
    sales_CGST_InMaha:any;
    sales_SGST_InMaha:any;
    sales_IGST_InMaha:any;
    sales_rate_OutMaha:any;
    sales_basic_OutMaha:any;
    sales_CGST_OutMaha:any;
    sales_SGST_OutMaha:any;
    sales_IGST_OutMaha:any;
    sales_basic_RCM:any;
    sales_CGST_RCM:any;
    sales_SGST_RCM:any;
    sales_IGST_RCM:any;
    sales_basic_Amendment:any;
    sales_CGST_Amendment:any;
    sales_SGST_Amendment:any;
    sales_IGST_Amendment:any;
    sales_Basic_Total:any;
    sales_CGST_Total: any;
    sales_SGST_Total: any;
    sales_IGST_Total: any;
    ITC_Basic: any;
    ITC_CGST: any;
    ITC_SGST: any;
    ITC_IGST: any;
    pur_inMhRt_18: any;
    pur_inMhBs_18: any;
    pur_inMhC_18: any;
    pur_inMhS_18: any;
    pur_inMhRt_12: any;
    pur_inMhBs_12: any;
    pur_inMhC_12: any;
    pur_inMhS_12: any;
    pur_inMhRt_5: any;
    pur_inMhBs_5: any;
    pur_inMhC_5: any;
    pur_inMhS_5: any;
    pur_OutMhRt_18: any;
    pur_OutMhBs_18: any;
    pur_OutMhI_18: any;
    pur_OutMhRt_12: any;
    pur_OutMhBs_12: any;
    pur_OutMhI_12: any;
    pur_OutMhRt_5: any;
    pur_OutMhBs_5: any;
    pur_OutMhI_5: any;
    purc_basic_Amendment: any;
    purc_CGST_Amendment: any;
    purc_SGST_Amendment: any;
    purc_IGST_Amendment: any;
    Pre_year_adj_CGST:any;
    Pre_year_adj_SGST:any;
    Pre_year_adj_IGST:any;
    pur_basic_total:any;
    pur_CGST_total:any;
    pur_SGST_total:any;
    pur_IGST_total:any;
    purc_RCM_CGST:any;
    purc_RCM_SGST:any;
    purc_RCM_IGST:any;
    IGST_to_IGST:any;
    IGST_to_CGST:any;
    IGST_to_SGST:any;
    CGST_Balance_Liability:any;
    SGST_Balance_Liability	:any;
    CGST_to_CGST:any;
    CGST_to_IGST:any;
    SGST_to_SGST:any;
    SGST_to_IGST:any;
    CGST_Late_Fees:any;
    SGST_Late_Fees:any;
    CGST_Final_Liability:any;
    SGST_Final_Liability:any;
    IGST_Final_Liability:any;
    IGST_Balance_Liability:any;
    Carried_Forward_CGST:any;
    Carried_Forward_SGST:any;
    Carried_Forward_IGST:any;
    month:any;
    year:any;
  pur_OutMhC_18: any;
  pur_OutMhC_12: any;
  pur_OutMhC_5: any;
  pur_OutMhS_18: any;
  pur_OutMhS_12: any;
  pur_OutMhS_5: any;
  purc_InMaha_Purc: any;
  purc_CGST_InMhPurc: any;
  purc_SGST_InMhPurc: any;
  purc_CGST_OutMhPurc: any;
  purc_SGST_OutMhPurc: any;
  purc_CGST_expenses: any;
  purc_SGST_expenses: any;
  payout_percentage: number;
  sales_rate_OutMaha_18: any;
  sales_basic_OutMaha_18: any;
  sales_CGST_OutMaha_18: any;
  sales_SGST_OutMaha_18: any;
  sales_IGST_OutMaha_18: any;
  sales_rate_OutMaha_12: any;
  sales_basic_OutMaha_12: any;
  sales_SGST_OutMaha_12: any;
  sales_CGST_OutMaha_12: any;
  sales_IGST_OutMaha_12: any;
  sales_rate_OutMaha_5: any;
  sales_basic_OutMaha_5: any;
  sales_CGST_OutMaha_5: any;
  sales_SGST_OutMaha_5: any;
  sales_IGST_OutMaha_5: any;
  Sales_RCM:any;
  Sales_Amendment: any;
  id: any;
  Purchase_RCM: number;
  PURC_Previous_year: number;
  Previous_Month_ITC: number;
  Late_Fees: number;
  Carried_Forward: number;
  Purchase_Amendment: number;
  object: any;
}