export class Monthlysalary{
    monthly_salary_id : any;
    user_id  : any;
    salary_package_id : any;
    salary_month : any;
    absent_days : any;
    no_of_late_marks : any;
    penalty_leave_days : any;
    extra_days : any;
    net_present_days : any;
    monthly_basic_salary : any;
    monthly_variable_pay : any;
    reimbursement : any;
    incentives : any;
    deduction : any;
    liabilities : any;
    total_pay : any;
    tds_deducted : any;
    net_pay : any;
    status : any;
    remark : any;
    paid_amount : any;
    payment_details : any;
    pending_amount : any;
}